### ISSUE TITLE
Add periodic table related functions

### ISSUE THREAD

**Issue by shravanasati** [mordy-python/chemyst#1]
I would like to contribute to *chemyst* by adding periodic table related functions like:
- [x] Electronic configuration of an element
- [x] Group number of an element
- [ ] Period number of an element

If you assign me this issue, I'd start working on the above-mentioned features.

**Comment by mordy-python** [comment]
Sounds great! Thanks for contributing!

**Comment by JordanLeich** [comment]
Hey there, I added in some stuff to your conversions.py file, stuff like conversations for temperatures Fahrenheit, celsius, and kelvin. If you assign me, I should be able to make a pull request and then you can look over all the changes I made. Overall, nice project!
