### ISSUE TITLE
Adding in more conversions

### ISSUE THREAD

**Issue by JordanLeich** [mordy-python/chemyst#2]
Hey there, I added in some stuff to your conversions.py file, stuff like conversations for temperatures Fahrenheit, celsius, and kelvin. If you assign me, I should be able to make a pull request and then you can look over all the changes I made. Also, if you would like me to add even more conversions for things such as weights like tons or pounds and all that, I can work on that as well. Overall, nice project!

**Comment by mordy-python** [comment]
Absolutely! Submit it and i'll commit it!
